#!/bin/bash
lock() {
    i3lock
}

case "$1" in
    lock)
        ~/.config/i3/lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        ~/.config/i3/lock && systemctl suspend
        ;;
    hibernate)
        ~/.config/i3/lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot -i
        ;;
    shutdown)
        systemctl poweroff -i
        ;;
    *)
        echo "Using: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
